import type { Metadata } from 'next';
import './globals.css';
import React, { JSX } from 'react';
import { Noto_Sans_KR } from 'next/font/google';
import { Header, Footer, Sidebar } from '@components';

const notoSans = Noto_Sans_KR({
  subsets: ['latin', 'cyrillic'],
  weight: ['300', '400', '500', '700'],
  variable: '--noto-sans-kr',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="ru">
      <body className={`${notoSans.variable} font-sans`}>
        <Header></Header>
        <Sidebar></Sidebar>
        <div>{children}</div>
        {}
        <Footer></Footer>
      </body>
    </html>
  );
}
